// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-K4HEL_DZWCb6TVysy6QvhGf5NXl-WO8',
    appId: '1:30509631384:web:6c84c2e9d096e35ca44ded',
    messagingSenderId: '30509631384',
    projectId: 'chat-app-5430d',
    authDomain: 'chat-app-5430d.firebaseapp.com',
    storageBucket: 'chat-app-5430d.appspot.com',
    measurementId: 'G-XS9HJBX1HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdGkR2PWnuhCWxDCleAbH0Z4AvXD9grHo',
    appId: '1:30509631384:android:d7fd9a4f517e2a63a44ded',
    messagingSenderId: '30509631384',
    projectId: 'chat-app-5430d',
    storageBucket: 'chat-app-5430d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9O52iK0hCwIQNH4lRuV5lrW-sG_yBTfA',
    appId: '1:30509631384:ios:59d5410fd47190dfa44ded',
    messagingSenderId: '30509631384',
    projectId: 'chat-app-5430d',
    storageBucket: 'chat-app-5430d.appspot.com',
    iosBundleId: 'com.example.project5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9O52iK0hCwIQNH4lRuV5lrW-sG_yBTfA',
    appId: '1:30509631384:ios:59d5410fd47190dfa44ded',
    messagingSenderId: '30509631384',
    projectId: 'chat-app-5430d',
    storageBucket: 'chat-app-5430d.appspot.com',
    iosBundleId: 'com.example.project5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-K4HEL_DZWCb6TVysy6QvhGf5NXl-WO8',
    appId: '1:30509631384:web:1b0412c73a7d487da44ded',
    messagingSenderId: '30509631384',
    projectId: 'chat-app-5430d',
    authDomain: 'chat-app-5430d.firebaseapp.com',
    storageBucket: 'chat-app-5430d.appspot.com',
    measurementId: 'G-97CNXWDJGS',
  );
}
